// <auto-generated />
using System;
using Auto.Konfiguration.Infrastructure.Daten;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auto.Konfiguration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324083900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.CarConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RimsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("PaintId");

                    b.HasIndex("RimsId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Motoren");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.OptionalEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarConfigurationId");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.Paint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lacke");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.Rims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Felgen");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.CarConfiguration", b =>
                {
                    b.HasOne("Auto.Konfiguration.Domain.Entities.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auto.Konfiguration.Domain.Entities.Paint", "Paint")
                        .WithMany()
                        .HasForeignKey("PaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auto.Konfiguration.Domain.Entities.Rims", "Rims")
                        .WithMany()
                        .HasForeignKey("RimsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Paint");

                    b.Navigation("Rims");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.OptionalEquipment", b =>
                {
                    b.HasOne("Auto.Konfiguration.Domain.Entities.CarConfiguration", null)
                        .WithMany("OptionalEquipment")
                        .HasForeignKey("CarConfigurationId");
                });

            modelBuilder.Entity("Auto.Konfiguration.Domain.Entities.CarConfiguration", b =>
                {
                    b.Navigation("OptionalEquipment");
                });
#pragma warning restore 612, 618
        }
    }
}
